version: '3.4'

services:
  app:
    image: supplier
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      DB_HOST: "database"
      DB_NAME: ""                 # WILL BE UPDATED
      DB_USER: ""                 # WILL BE UPDATED
      DB_PASS: ""                 # WILL BE UPDATED
    depends_on:
      - database
    networks:
      - supplier

  database:
    image: "mysql:8.0.28"
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: ""          # WILL BE UPDATED
      MYSQL_ROOT_PASSWORD: ""     # WILL BE UPDATED
    networks:
      - supplier

networks:
  supplier:
    driver: bridge